# Generated by Django 5.2 on 2025-05-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="create_time",
        ),
        migrations.RemoveField(
            model_name="action",
            name="update_time",
        ),
        migrations.RemoveField(
            model_name="actionplan",
            name="create_time",
        ),
        migrations.RemoveField(
            model_name="actionplan",
            name="update_time",
        ),
        migrations.RemoveField(
            model_name="cumulativelifemeaning",
            name="create_time",
        ),
        migrations.RemoveField(
            model_name="cumulativelifemeaning",
            name="update_time",
        ),
        migrations.RemoveField(
            model_name="lifemeaning",
            name="create_time",
        ),
        migrations.RemoveField(
            model_name="lifemeaning",
            name="update_time",
        ),
        migrations.RemoveField(
            model_name="metaaction",
            name="create_time",
        ),
        migrations.RemoveField(
            model_name="metaaction",
            name="update_time",
        ),
        migrations.RemoveField(
            model_name="metaactioncategory",
            name="create_time",
        ),
        migrations.RemoveField(
            model_name="metaactioncategory",
            name="update_time",
        ),
        migrations.RemoveField(
            model_name="metaactioncategorymapping",
            name="create_time",
        ),
        migrations.RemoveField(
            model_name="metaactioncategorymapping",
            name="update_time",
        ),
        migrations.RemoveField(
            model_name="metaactioncausationvaluegoal",
            name="create_time",
        ),
        migrations.RemoveField(
            model_name="metaactioncausationvaluegoal",
            name="update_time",
        ),
        migrations.RemoveField(
            model_name="metaactioninteractionmetaaction",
            name="create_time",
        ),
        migrations.RemoveField(
            model_name="metaactioninteractionmetaaction",
            name="update_time",
        ),
        migrations.RemoveField(
            model_name="valuegoal",
            name="create_time",
        ),
        migrations.RemoveField(
            model_name="valuegoal",
            name="update_time",
        ),
        migrations.RemoveField(
            model_name="valuegoalcategory",
            name="create_time",
        ),
        migrations.RemoveField(
            model_name="valuegoalcategory",
            name="update_time",
        ),
        migrations.RemoveField(
            model_name="valuegoalweight",
            name="create_time",
        ),
        migrations.RemoveField(
            model_name="valuegoalweight",
            name="update_time",
        ),
        migrations.RemoveField(
            model_name="valuesystempriority",
            name="create_time",
        ),
        migrations.RemoveField(
            model_name="valuesystempriority",
            name="update_time",
        ),
    ]
