# Generated by Django 5.2 on 2025-05-19 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goal", "0002_cumulativelifemeaning_accumulated_meaning_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cumulativelifemeaning",
            name="action_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cumulative_lifemeanings",
                to="goal.actionplan",
            ),
        ),
    ]
