# Generated by Django 5.2 on 2025-05-19 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goal", "0003_alter_cumulativelifemeaning_action_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cumulativelifemeaning",
            name="action_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="goal.actionplan",
            ),
        ),
        migrations.AlterField(
            model_name="cumulativelifemeaning",
            name="value_system_priority",
            field=models.FloatField(default=0.0),
        ),
    ]
