# Generated by Django 5.2 on 2025-05-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goal", "0004_alter_cumulativelifemeaning_action_plan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cumulativelifemeaning",
            name="life_meaning_history",
            field=models.JSONField(default=list, verbose_name="人生意义历史记录"),
        ),
    ]
