# Generated by Django 5.2 on 2025-05-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goal", "0005_cumulativelifemeaning_life_meaning_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="valuesystempriority",
            name="lifespan_stages",
            field=models.JSONField(default=list, verbose_name="生命周期阶段"),
        ),
    ]
